filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'vendor/'

build:
  dependencies:
    override:
      - composer self-update --no-interaction --no-progress
      - composer remove squizlabs/php_codesniffer friendsofphp/php-cs-fixer phpstan/phpstan --dev --no-interaction --no-progress --no-update
      - composer install --no-interaction --prefer-dist
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/ 
      project_setup: {override: true}
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
