language: php

# php compatibility
php: ["7.3", "7.4", "8.0"]

cache:
  - directories:
    - $HOME/.composer
    - $HOME/.phive

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update --no-interaction --2
  - travis_retry composer upgrade --no-interaction --prefer-dist
  - wget -O phive https://phar.io/releases/phive.phar && chmod +x phive
  - ./phive install --force-accept-unsigned --trust-gpg-keys 0x4AA394086372C20A,0x31C7E470E2138192,0xE82B2FB314E9906E,0xCF1A108D0E7AE720,0xC5095986493B4AA0

script:
  - PHP_CS_FIXER_IGNORE_ENV=yes tools/php-cs-fixer fix --dry-run --verbose
  - tools/phpcs --colors -sp src/ tests/ bin/
  - vendor/bin/phpunit --testdox --verbose
  - tools/phpstan analyse --no-progress --verbose --level max src/ tests/  bin/
  - bash bin/check-current-max-occurs-paths.bash

notifications:
  email:
    if: branch = main

